name: namer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5+1
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  youtube_explode_dart: ^3.1.0
  path_provider: ^2.1.6
  just_audio_background: ^0.0.1-beta.17
  flutter_launcher_icons: ^0.14.4
  ytmusicapi_dart: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "logo.png"

